name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini



  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_NOMBRE=nombre1
      - CLI_APELLIDO=apellido1
      - CLI_DOCUMENTO=39000000
      - CLI_NACIMIENTO=1990-01-01
      - CLI_NUMERO=5000
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_NOMBRE=nombre2
      - CLI_APELLIDO=apellido2
      - CLI_DOCUMENTO=39000001
      - CLI_NACIMIENTO=1990-01-01
      - CLI_NUMERO=5001
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_NOMBRE=nombre3
      - CLI_APELLIDO=apellido3
      - CLI_DOCUMENTO=39000002
      - CLI_NACIMIENTO=1990-01-01
      - CLI_NUMERO=5002
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_NOMBRE=nombre4
      - CLI_APELLIDO=apellido4
      - CLI_DOCUMENTO=39000003
      - CLI_NACIMIENTO=1990-01-01
      - CLI_NUMERO=5003
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_NOMBRE=nombre5
      - CLI_APELLIDO=apellido5
      - CLI_DOCUMENTO=39000004
      - CLI_NACIMIENTO=1990-01-01
      - CLI_NUMERO=5004
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24